spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/recetin_db
spring.datasource.username=recetin_user
spring.datasource.password=recetin_pass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

# CONFIGURACION SERVICIO DE CORREO
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# IMAGENES MAS GRANDES
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
